# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker buildx build -t alastairhm/contextfree:latest .
    silent: true
  push:
    cmds:
      - docker push alastairhm/contextfree:latest 
    silent: true
  test:
    cmds:
      - docker run --rm -v ${PWD}:/mnt alastairhm/contextfree -s1024 input_file.cfdg output.png
    silent: true
