# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker buildx build -t alastairhm/contextfree:latest .
    silent: true
  push:
    cmds:
      - docker push alastairhm/contextfree:latest 
    silent: true
